name: dicore_modal
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DicoreModalPlugin
      macos:
        pluginClass: DicoreModalPlugin
      android:
        package: com.dicore.dicore_modal
        pluginClass: DicoreModalPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
